version: '3.4'

services:
  webapiacktest:
    image: webapiacktest:dev
    container_name: WebApiAckTest
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "WebApiAckTest"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_webapiacktest$
    volumes:
      - C:\Users\anup4\source\repos\ACKTest\WebApiAckTest:/app
      - C:\Users\anup4\source\repos\ACKTest:/src
      - C:\Users\anup4\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_webapiacktest$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_webapiacktest$ \"/app/bin/Debug/net5.0/WebApiAckTest.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
  webappacktest:
    image: webappacktest:dev
    container_name: WebAppAckTest
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "WebAppAckTest"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_webappacktest$
    volumes:
      - C:\Users\anup4\source\repos\ACKTest\WebAppAckTest:/app
      - C:\Users\anup4\source\repos\ACKTest:/src
      - C:\Users\anup4\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_webappacktest$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_webappacktest$ \"/app/bin/Debug/net5.0/WebAppAckTest.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true
